# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{hoptoad-api}
  s.version = "2.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Steve Agalloco"]
  s.date = %q{2010-04-23}
  s.description = %q{An unofficial gem for interacting with the Hoptoad API}
  s.email = %q{steve.agalloco@gmail.com}
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    ".gitignore",
     "README.textile",
     "Rakefile",
     "hoptoad-api.gemspec",
     "lib/hoptoad-api.rb",
     "lib/hoptoad-api/client.rb",
     "lib/hoptoad-api/core_extensions.rb",
     "lib/hoptoad-api/version.rb",
     "test/fixtures/errors.xml",
     "test/fixtures/individual_error.xml",
     "test/fixtures/paginated_errors.xml",
     "test/test_helper.rb",
     "test/test_hoptoad-api.rb"
  ]
  s.homepage = %q{http://github.com/spagalloco/hoptoad-api}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{An unofficial gem for interacting with the Hoptoad API}
  s.test_files = [
    "test/test_helper.rb",
     "test/test_hoptoad-api.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, [">= 0.5.2"])
      s.add_runtime_dependency(%q<hashie>, [">= 0.2.0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<fakeweb>, [">= 0"])
    else
      s.add_dependency(%q<httparty>, [">= 0.5.2"])
      s.add_dependency(%q<hashie>, [">= 0.2.0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<fakeweb>, [">= 0"])
    end
  else
    s.add_dependency(%q<httparty>, [">= 0.5.2"])
    s.add_dependency(%q<hashie>, [">= 0.2.0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<fakeweb>, [">= 0"])
  end
end

